site_name: Postgres Controller
plugins:
  - search
  - markdownextradata
#  - mkdocs_pymdownx_material_extras
  - codeinclude:
      title_mode: none #pymdownx.tabbed
theme:
  name: 'material'
  palette:
    primary: 'light blue'
    accent: 'light blue'
  font: false
  #logo: 'assets/logo.svg'
  #favicon: 'assets/logo.ico'
repo_name: 'postgres-operator'
repo_url: 'https://github.com/brose-ebike/postgres-operator'
markdown_extensions:
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
nav:
  - Introduction: index.md
  - Installation: 
    - Introduction: installation/index.md
    - Kubectl apply: installation/simple.md
    - Helm: installation/helm.md
    - Kustomize: installation/kustomize.md
  - Usage: 
    - Introduction: usage/index.md
    - Create Instance: usage/instance.md
    - Create Database: usage/database.md
    - Create User: usage/user.md
    - ArgoCD: usage/argocd.md
  - Contribution: contribution.md
extra:
  latest_version: 0.0.1
