apiVersion: postgres.brose.bike/v1
kind: PgInstance
metadata:
  name: my-instance
spec:
  host:
    secretKeyRef: 
      name: "my-secret"
      key: "hostname"
  port:
    secretKeyRef: 
      name: "my-secret"
      key: "port"
  username:
    secretKeyRef: 
      name: "my-secret"
      key: "user"
  password:
    secretKeyRef: 
      name: "my-secret"
      key: "password"
  database:
    secretKeyRef: 
      name: "my-secret"
      key: "dbname"
  sslMode:
    secretKeyRef: 
      name: "my-secret"
      key: "sslmode"
    