# permissions for end users to edit pgdatabases.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pgdatabase-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: postgres-operator
    app.kubernetes.io/part-of: postgres-operator
    app.kubernetes.io/managed-by: kustomize
  name: pgdatabase-editor-role
rules:
- apiGroups:
  - postgres.brose.bike
  resources:
  - pgdatabases
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.brose.bike
  resources:
  - pgdatabases/status
  verbs:
  - get
