# permissions for end users to view pgusers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pguser-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: postgres-controller
    app.kubernetes.io/part-of: postgres-controller
    app.kubernetes.io/managed-by: kustomize
  name: pguser-viewer-role
rules:
- apiGroups:
  - postgres.brose.bike
  resources:
  - pgusers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - postgres.brose.bike
  resources:
  - pgusers/status
  verbs:
  - get
