---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.oebc.tools
  resources:
  - pgbackupinstances
  - pgbackuppolicies
  - pgdatabases
  - pginstances
  - pgusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - postgres.oebc.tools
  resources:
  - pgbackupinstances/finalizers
  - pgbackuppolicies/finalizers
  - pgdatabases/finalizers
  - pginstances/finalizers
  - pgusers/finalizers
  verbs:
  - update
- apiGroups:
  - postgres.oebc.tools
  resources:
  - pgbackupinstances/status
  - pgbackuppolicies/status
  - pgdatabases/status
  - pginstances/status
  - pgusers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterrolebindings
  - clusterroles
  - rolebindings
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
