apiVersion: postgres.brose.bike/v1
kind: PgUser
metadata:
  labels:
    app.kubernetes.io/name: pguser
    app.kubernetes.io/instance: pguser-sample
    app.kubernetes.io/part-of: postgres-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: postgres-controller
  name: pguser-sample
spec:
  # TODO(user): Add fields here
