apiVersion: postgres.brose.bike/v1
kind: PgDatabase
metadata:
  labels:
    app.kubernetes.io/name: pgdatabase
    app.kubernetes.io/instance: pgdatabase-sample
    app.kubernetes.io/part-of: postgres-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: postgres-operator
  name: mydb
spec:
  instance:
    namespace: "default"
    name: "my-instance"
  deletion:
    drop: false # optional, default false
    wait: false # optional, default false
  defaultPrivileges: []
  publicPrivileges:
    revoke: false # optional, default false
  publicSchema:
    drop: false # optional, default false