apiVersion: postgres.brose.bike/v1
kind: PgInstance
metadata:
  labels:
    app.kubernetes.io/name: pginstance
    app.kubernetes.io/instance: pginstance-sample
    app.kubernetes.io/part-of: postgres-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: postgres-operator
  name: my-instance
spec:
  host:
    secretKeyRef: 
      name: "my-secret"
      key: "hostname"
  port:
    secretKeyRef: 
      name: "my-secret"
      key: "port"
  username:
    secretKeyRef: 
      name: "my-secret"
      key: "user"
  password:
    secretKeyRef: 
      name: "my-secret"
      key: "password"
  database:
    secretKeyRef: 
      name: "my-secret"
      key: "dbname"
  sslMode:
    secretKeyRef: 
      name: "my-secret"
      key: "sslmode"
    