apiVersion: postgres.brose.bike/v1
kind: PgInstance
metadata:
  labels:
    app.kubernetes.io/name: pginstance
    app.kubernetes.io/instance: pginstance-sample
    app.kubernetes.io/part-of: postgres-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: postgres-controller
  name: pginstance-sample
spec:
  host:
    value: "localhost"
    configMapKeyRef:
      name: "my-config-map"
      key: "hostname"
      optional: false
    secretKeyRef: 
      name: "my-secret"
      key: "hostname"
      optional: false
  port:
    value: "5432"
    configMapKeyRef:
      name: "my-config-map"
      key: "port"
      optional: false
    secretKeyRef: 
      name: "my-secret"
      key: "port"
      optional: false
  username:
    value: "admin"
    configMapKeyRef:
      name: "my-config-map"
      key: "username"
      optional: false
    secretKeyRef: 
      name: "my-secret"
      key: "username"
      optional: false
  password:
    value: "password"
    configMapKeyRef:
      name: "my-config-map"
      key: "password"
      optional: false
    secretKeyRef: 
      name: "my-secret"
      key: "password"
      optional: false
