apiVersion: postgres.brose.bike/v1
kind: PgUser
metadata:
  labels:
    app.kubernetes.io/name: pguser
    app.kubernetes.io/instance: pguser-sample
    app.kubernetes.io/part-of: postgres-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: postgres-operator
  name: myuser
spec:
  instance:
    namespace: "default"
    name: "my-instance"
  secret: # optional value
    name: "dummy" # optional value
  databases: 
  # case 1: role is db owner
    - name: "mydb"
      owner: true # optional,  default=false
      privileges: ["CONNECT", "CREATE"]
  # case 2: loginrole has specific privs
  #  - name: "cashflowdb"
  #    privileges: ["CONNECT", "CREATE", "TEMPLATE", "TEMPORARY"]
  #    schemas:
  #      - name: "service"
  #        owner: true # optional,  default=false
  #      - name: "monolith"
  #        privileges: ["USAGE", "CREATE"]
  #        # TODO(other priv): Add support for sequence, function or procedure
  #        tables: 
  #          - name: "bikes"
  #            owner: true # optional,  default=false
  #          - name: "rides"
  #            privileges: ["SELECT", "INSERT", "UPDATE", "DELETE", "TRUNCATE"]
    # TODO(label): Add filter instance by label
  # TODO(password): Add password rule section