name: Release
on:
  workflow_dispatch:


jobs:
  release:
    name: "Create Release"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: "cd-build-${{ github.ref }}"
      cancel-in-progress: true
    steps:
      ########################################################################################################################
      ########################################### Setup ######################################################################
      ########################################################################################################################
      - uses: actions/checkout@v3
      - id: cache-tools
        name: Cache Tools
        uses: actions/cache@v3
        with:
          path: bin/
          key: ${{ runner.os }}-${{ hashFiles('Makefile') }}
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Get current date
        id: params
        run: |
          echo "latest=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_OUTPUT
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT
      ########################################################################################################################
      ########################################### Build ######################################################################
      ########################################################################################################################
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}         
      - name: "Build Docker Image"
        run: make docker-build #docker-push IMG=
      - name: "Build Controller Binaries and Resource Definitions"
        run: make release
      ########################################################################################################################
      ########################################### Release#####################################################################
      ########################################################################################################################
      - id: content
        name: Create Release Content
        uses: raynigon/release-documentation@main
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          latest: "${{ steps.params.outputs.latest }}"
          templateFile: ".github/templates/release.txt"
      - name: "Github Release"
        uses: softprops/action-gh-release@91409e712cf565ce9eff10c87a8d1b11b81757ae #v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          tag_name: "v${{ steps.params.outputs.version }}"
          name: "v${{ steps.params.outputs.version }}"
          files: dist/*
          body: ${{ steps.content.outputs.content }}
      - name: Increment Version
        run: python .github/scripts/increment_version.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: 'Release ${{ steps.params.outputs.version }}'
          branch: release-${{ steps.params.outputs.version }}
          commit-message: Release ${{ steps.params.outputs.version }} on ${{ steps.params.outputs.date }}
          delete-branch: true
          draft: false
          labels: |
            release
          reviewers: |
            raynigon
            dbalucas

  documentation:
    name: "Update Documentation"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: ["release"]
    concurrency:
      group: "cd-documentation-${{ github.ref }}"
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip3 install -r requirements.txt
      - run: mkdocs gh-deploy


