name: Release
on:
  workflow_dispatch:


jobs:
  release:
    name: "Create Release"
    runs-on: ubuntu-latest
    timeout-minutes: 30
    concurrency:
      group: "cd-build-${{ github.ref }}"
      cancel-in-progress: true
    steps:
      ########################################################################################################################
      ########################################### Setup ######################################################################
      ########################################################################################################################
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
      - id: cache-tools
        name: Cache Tools
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9
        with:
          path: bin/
          key: ${{ runner.os }}-${{ hashFiles('Makefile') }}
      - name: Set up Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: '3.x'
      - name: Get current date
        id: params
        run: |
          echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "version=$(cat version.txt)" >> $GITHUB_OUTPUT
      ########################################################################################################################
      ########################################### Build ######################################################################
      ########################################################################################################################
      - name: Login to Docker Hub
        uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f
        with:
          registry: "ghcr.io"
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: "Build Controller"
        run: make release "IMG=ghcr.io/brose-ebike/postgres-operator:v${{ steps.params.outputs.version }}"
      ########################################################################################################################
      ########################################### Release#####################################################################
      ########################################################################################################################
      - name: Tag Release
        run: git tag "v${{ steps.params.outputs.version }}"
      - id: content
        name: Create Release Content
        uses: raynigon/release-documentation@cc6d191c791ae349b003405670841ff9a5866e9b
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          latest: "v${{ steps.params.outputs.version }}"
          templateFile: ".github/templates/release.md"
      - name: "Github Release"
        uses: softprops/action-gh-release@efb35369e0ad2afab669f228072c1b0d510eae64 #v1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          tag_name: "v${{ steps.params.outputs.version }}"
          name: "v${{ steps.params.outputs.version }}"
          files: dist/*
          body: ${{ steps.content.outputs.content }}
      - name: Increment Version
        run: python .github/scripts/increment_version.py
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1
        with:
          title: 'Release ${{ steps.params.outputs.version }}'
          branch: release-${{ steps.params.outputs.version }}
          commit-message: Release ${{ steps.params.outputs.version }} on ${{ steps.params.outputs.date }}
          delete-branch: true
          draft: false
          labels: |
            release
          reviewers: |
            raynigon
            dbalucas

  documentation:
    name: "Update Documentation"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    needs: ["release"]
    concurrency:
      group: "cd-documentation-${{ github.ref }}"
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97
        with:
          python-version: '3.x'
      - run: pip3 install -r requirements.txt
      - run: mkdocs gh-deploy


