name: CI
on:
  push:
    branches: [main]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: "build-${{ github.ref }}"
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - id: cache-tools
        name: Cache Tools
        uses: actions/cache@v3
        with:
          path: bin/
          key: ${{ runner.os }}-${{ hashFiles('Makefile') }}
      - name: "Build Docker Image"
        run: |
          make docker-build

  documentation:
    name: "Documentation"
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency:
      group: "documentation-${{ github.ref }}"
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - run: pip3 install -r requirements.txt
      - run: mkdocs gh-deploy

